#!/usr/bin/env python3
"""gen_skycube.py - procedural atmospheric sky cubemap generator.

Produces a 6-face cubemap (one PNG per face) for a sky "preset" -- the
atmospheric portion of the sky (color gradient, banded horizon).  Sun,
moon, and stars live on a separate rotating celestial overlay cube
generated by gen_celestialcube.py; this script does NOT bake them into
the atmospheric textures.

Cubemap convention: faces are written as <prefix>_<face>.png where <face> is
one of {posx, negx, posy, negy, posz, negz}, matching D3D / OpenGL cube face
order. The +Z face looks straight up (toward the zenith), -Z faces straight
down (toward the nadir). The four side faces wrap horizontally.

Per-preset content:
    day    - bright blue zenith fading to warm horizon
    dusk   - oranges/purples banded at horizon, dim upper sky
    night  - deep blue zenith fading to almost-black horizon

Requires: numpy, Pillow.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image


# ----------------------------------------------------------------------------
# Per-face direction generator.
#
# For a face of size N x N, returns an (N, N, 3) array of unit-length world
# direction vectors. Each face is centered on its axis with the other two
# axes spanning [-1, 1].
# ----------------------------------------------------------------------------

def face_directions(face: str, size: int) -> np.ndarray:
    """Returns (N, N, 3) of unit-vector directions for the named cube face."""
    # Build u, v in [-1, 1] where (u, v) = (0, 0) is the face center.
    u = np.linspace(-1.0, 1.0, size, dtype=np.float64)
    v = np.linspace(-1.0, 1.0, size, dtype=np.float64)
    uu, vv = np.meshgrid(u, v, indexing='xy')

    # D3D cube face conventions (looking outward from the cube center):
    #   posx: +X face, u -> -Z, v -> -Y
    #   negx: -X face, u -> +Z, v -> -Y
    #   posy: +Y face, u -> +X, v -> +Z
    #   negy: -Y face, u -> +X, v -> -Z
    #   posz: +Z face, u -> +X, v -> -Y
    #   negz: -Z face, u -> -X, v -> -Y
    if face == 'posx':
        x = np.ones_like(uu); y = -vv;          z = -uu
    elif face == 'negx':
        x = -np.ones_like(uu); y = -vv;         z = uu
    elif face == 'posy':
        x = uu;                y = np.ones_like(uu); z = vv
    elif face == 'negy':
        x = uu;                y = -np.ones_like(uu); z = -vv
    elif face == 'posz':
        x = uu;                y = -vv;         z = np.ones_like(uu)
    elif face == 'negz':
        x = -uu;               y = -vv;         z = -np.ones_like(uu)
    else:
        raise ValueError(f"unknown face '{face}'")

    dir = np.stack([x, y, z], axis=-1)
    norm = np.linalg.norm(dir, axis=-1, keepdims=True)
    return dir / np.maximum(norm, 1e-9)


# ----------------------------------------------------------------------------
# Sky gradient evaluation.
#
# Each preset is a function from (direction, elevation) to linear RGB. The
# elevation is dir.z = sin(altitude angle). +1 = zenith, 0 = horizon,
# -1 = nadir.
# ----------------------------------------------------------------------------

def smoothstep(a: float, b: float, t: np.ndarray) -> np.ndarray:
    x = np.clip((t - a) / (b - a), 0.0, 1.0)
    return x * x * (3.0 - 2.0 * x)


def sky_day(dirs: np.ndarray) -> np.ndarray:
    """Bright blue zenith fading to warm horizon."""
    z = dirs[..., 2]
    above = np.clip(z, 0.0, 1.0)
    below = np.clip(-z, 0.0, 1.0)

    zenith   = np.array([0.20, 0.40, 0.80])
    horizon  = np.array([0.65, 0.78, 0.90])
    ground   = np.array([0.10, 0.10, 0.12])

    t_up = smoothstep(0.0, 0.6, above)
    upper = horizon[None, None, :] * (1.0 - t_up[..., None]) + zenith[None, None, :] * t_up[..., None]

    t_dn = smoothstep(0.0, 0.4, below)
    lower = horizon[None, None, :] * (1.0 - t_dn[..., None]) + ground[None, None, :] * t_dn[..., None]

    return np.where(z[..., None] >= 0.0, upper, lower)


def sky_dusk(dirs: np.ndarray) -> np.ndarray:
    """Banded oranges/purples at horizon, dim violet upper sky."""
    z = dirs[..., 2]
    above = np.clip(z, 0.0, 1.0)
    below = np.clip(-z, 0.0, 1.0)

    zenith   = np.array([0.10, 0.08, 0.22])
    horizon_warm = np.array([0.95, 0.45, 0.20])
    horizon_cool = np.array([0.40, 0.18, 0.38])
    ground   = np.array([0.04, 0.03, 0.06])

    # Two horizon bands: a warm strip just above the horizon, a cooler one
    # higher up.
    warm = smoothstep(0.0, 0.08, above) * (1.0 - smoothstep(0.0, 0.20, above))
    cool = smoothstep(0.15, 0.45, above)

    upper = (zenith[None, None, :] * (1.0 - cool[..., None])
             + horizon_warm[None, None, :] * warm[..., None] * 0.7
             + horizon_cool[None, None, :] * cool[..., None] * 0.6)

    t_dn = smoothstep(0.0, 0.4, below)
    lower = horizon_cool[None, None, :] * (1.0 - t_dn[..., None]) + ground[None, None, :] * t_dn[..., None]

    return np.where(z[..., None] >= 0.0, upper, lower)


def sky_night(dirs: np.ndarray) -> np.ndarray:
    """Deep blue zenith fading to near-black horizon.

    Stars are no longer baked into the night gradient; they live on a
    separate rotating celestial cube (see gen_celestialcube preset) so
    they move with the moon across the diurnal cycle instead of being
    pinned to fixed cube faces.
    """
    z = dirs[..., 2]
    above = np.clip(z, 0.0, 1.0)
    below = np.clip(-z, 0.0, 1.0)

    zenith   = np.array([0.02, 0.04, 0.10])
    horizon  = np.array([0.06, 0.08, 0.16])
    ground   = np.array([0.01, 0.01, 0.02])

    t_up = smoothstep(0.0, 0.6, above)
    upper = horizon[None, None, :] * (1.0 - t_up[..., None]) + zenith[None, None, :] * t_up[..., None]

    t_dn = smoothstep(0.0, 0.4, below)
    lower = horizon[None, None, :] * (1.0 - t_dn[..., None]) + ground[None, None, :] * t_dn[..., None]

    return np.where(z[..., None] >= 0.0, upper, lower)


# ----------------------------------------------------------------------------
# Driver
# ----------------------------------------------------------------------------

FACES = ('posx', 'negx', 'posy', 'negy', 'posz', 'negz')

PRESETS = {
    'day':   sky_day,
    'dusk':  sky_dusk,
    'night': sky_night,
}


def linear_to_srgb(c: np.ndarray) -> np.ndarray:
    return np.clip(c, 0.0, 1.0) ** (1.0 / 2.2)


def write_png_rgb8(arr01: np.ndarray, path: Path) -> None:
    u8 = (np.clip(arr01, 0.0, 1.0) * 255.0 + 0.5).astype(np.uint8)
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(u8, mode='RGB').save(path, format='PNG')


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description='Procedural atmospheric sky cubemap generator.')
    p.add_argument('--preset', choices=sorted(PRESETS.keys()), required=True,
                   help='Which sky preset to generate')
    p.add_argument('--face-size', type=int, default=512, help='Per-face size in texels (default 512)')
    p.add_argument('--seed', type=int, default=1, help='Random seed (reserved for future presets)')
    p.add_argument('--out-dir', type=Path, required=True,
                   help='Output directory (cube faces written as sky_<preset>_<face>.png)')
    args = p.parse_args(argv)

    if args.face_size < 8:
        print('error: --face-size must be >= 8', file=sys.stderr)
        return 2

    sky_fn = PRESETS[args.preset]

    for face in FACES:
        dirs = face_directions(face, args.face_size)
        rgb  = sky_fn(dirs)
        rgb_srgb = linear_to_srgb(rgb)
        out_path = args.out_dir / f'sky_{args.preset}_{face}.png'
        write_png_rgb8(rgb_srgb, out_path)
        print(f'wrote {out_path}')

    print(f'  preset={args.preset}, face_size={args.face_size}, seed={args.seed}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
